/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rs_meterial_counter_dataproc */

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jbyteArray JNICALL Java_com_rs_optometry_1gateway_Optometry_1code_TranInt2Short
  (JNIEnv *env, jclass obj, jint mData);

JNIEXPORT jbyte JNICALL Java_com_rs_optometry_1gateway_Optometry_1code_TranInt2Char
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
